name: weather_appp
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.6.0


dependencies:
  flutter:
    sdk: flutter
  internet_connection_checker: ^3.0.1

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  dartz: ^0.10.1
  http: ^1.3.0
  flutter_bloc: ^9.1.0
  intl: ^0.20.2
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  provider: ^6.1.4
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  

flutter:
  assets:
    - assets/icons/

  uses-material-design: true



